internal/licenses: remove exceptions
With the recent changes to licensecheck and our lists of acceptable
licenses and filename, we no longer need exceptions (with one
exception: see below).

- Now that we recognize the filenames UNLICENSE and LICENSE-MIT, and
  we treat the Unlicense as redistributable, the gioui.org repo is no
  longer a special case.

- Reducing coverage to 75% catches the Canonical license.

- Improvements to variable-text detection in licensecheck mean we can
  recognize the Gonum license as BSD-3.

Changes in this CL:

- Remove the exception code.

- We still have a problem: the gioui.org module has a COPYING file
  that is not a valid license. (We told the author to add it.)
  Arrange to ignore that file.

- Check these changes against the result of exception processing in
  prod. We can do that with some additions to the "license changes"
  command, also in this CL.

Change-Id: Ib3f738ee2ca3332cd23fa3a2f9837836536f6ca4
Reviewed-on: https://team-review.git.corp.google.com/c/golang/discovery/+/666955
CI-Result: Cloud Build <devtools-proctor-result-processor@system.gserviceaccount.com>
Reviewed-by: Julie Qiu <julieqiu@google.com>