Revert "migrations: use expression index on package_symbols"
This reverts commit a86acb4ac3739843729901b722c978442a0cc641.

Reason for revert: sha256 fails when casting non-utf8 strings.

For example:

discovery-db=# SELECT sha256('[]byte(\x00)'::bytea);
ERROR:  invalid input syntax for type bytea
LINE 1: SELECT sha256('[]byte(\x00)'::bytea);


                      ^

This is fine when using uuid_generate_v5, so reverting back to that
implementation for the expression index:

discovery-db=# SELECT uuid_generate_v5(uuid_nil(), '[]byte(\x00)');
           uuid_generate_v5
--------------------------------------
 84427504-1416-50ae-9f12-e562e86f4408
(1 row)

Change-Id: I3abd756ee0749eae32bb25cfa32e982d4c92c37a
Reviewed-on: https://go-review.googlesource.com/c/pkgsite/+/299329
Reviewed-by: Jamal Carvalho <jamal@golang.org>
Trust: Julie Qiu <julie@golang.org>
Run-TryBot: Julie Qiu <julie@golang.org>