cmd/fetch: handle /favicon.ico requests
The /favicon.ico route is handled explicity and no longer returns the
error: ParseModulePathAndVersion("/favicon.ico"): invalid path: "/favicon.ico"

Fixes b/129903914

Change-Id: I0044bf485d2d145e85d6ab2f90e82eece7305eab
Reviewed-on: https://team-review.git.corp.google.com/c/golang/discovery/+/450682
Reviewed-by: Robert Findley <rfindley@google.com>